name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: test
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode_13.0.app
      - name: Run tests
        run: make test
